version: '3.7'
services:

  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/nuclear
    command: bash -xc "
              npm run watch; npm run electron:dev"

  storybook:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - "6006:6006"
    volumes:
      - .:/app
    command: bash -xc "
              lerna link;
              lerna exec yarn install;
              lerna run storybook:ci --scope @cyc/storybook --stream"
